global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Personal Notes System Application
  - job_name: 'personal-notes-app'
    static_configs:
      - targets: ['app:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # MySQL Database
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']
    scrape_interval: 30s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # WebSocket Server
  - job_name: 'websocket'
    static_configs:
      - targets: ['websocket:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Background Worker
  - job_name: 'worker'
    static_configs:
      - targets: ['worker:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx Load Balancer
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-lb:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s
