apiVersion: v1
kind: Namespace
metadata:
  name: personal-notes
  labels:
    name: personal-notes
    app: personal-notes-system
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: personal-notes-quota
  namespace: personal-notes
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: personal-notes-limits
  namespace: personal-notes
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
